CREATE TABLE mytable(
   id                  INTEGER  NOT NULL PRIMARY KEY 
  ,kode_provinsi       INTEGER  NOT NULL
  ,nama_provinsi       VARCHAR(10) NOT NULL
  ,kode_kabupaten_kota INTEGER  NOT NULL
  ,nama_kabupaten_kota VARCHAR(23) NOT NULL
  ,jumlah_dokter_umum  INTEGER  NOT NULL
  ,satuan              VARCHAR(5) NOT NULL
  ,tahun               INTEGER  NOT NULL
);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (1,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',524,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (2,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',87,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (3,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',119,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (4,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',180,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (5,32,'JAWA BARAT',3205,'KABUPATEN GARUT',125,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (6,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',78,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (7,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',29,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (8,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',114,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (9,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',219,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (10,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',94,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (11,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',127,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (12,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',128,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (13,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',69,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (14,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',81,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (15,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',219,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (16,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',325,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (17,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',215,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (18,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',18,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (19,32,'JAWA BARAT',3271,'KOTA BOGOR',301,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (20,32,'JAWA BARAT',3272,'KOTA SUKABUMI',115,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (21,32,'JAWA BARAT',3273,'KOTA BANDUNG',483,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (22,32,'JAWA BARAT',3274,'KOTA CIREBON',112,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (23,32,'JAWA BARAT',3275,'KOTA BEKASI',281,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (24,32,'JAWA BARAT',3276,'KOTA DEPOK',368,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (25,32,'JAWA BARAT',3277,'KOTA CIMAHI',150,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (26,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',101,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (27,32,'JAWA BARAT',3279,'KOTA BANJAR',33,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (28,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',605,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (29,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',84,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (30,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',76,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (31,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',246,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (32,32,'JAWA BARAT',3205,'KABUPATEN GARUT',196,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (33,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',54,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (34,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',70,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (35,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',115,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (36,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',255,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (37,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',115,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (38,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',78,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (39,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',147,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (40,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',100,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (41,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',131,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (42,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',326,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (43,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',269,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (44,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',89,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (45,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',17,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (46,32,'JAWA BARAT',3271,'KOTA BOGOR',320,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (47,32,'JAWA BARAT',3272,'KOTA SUKABUMI',126,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (48,32,'JAWA BARAT',3273,'KOTA BANDUNG',137,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (49,32,'JAWA BARAT',3274,'KOTA CIREBON',94,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (50,32,'JAWA BARAT',3275,'KOTA BEKASI',133,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (51,32,'JAWA BARAT',3276,'KOTA DEPOK',136,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (52,32,'JAWA BARAT',3277,'KOTA CIMAHI',167,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (53,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',0,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (54,32,'JAWA BARAT',3279,'KOTA BANJAR',56,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (55,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',580,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (56,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',188,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (57,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',76,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (58,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',644,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (59,32,'JAWA BARAT',3205,'KABUPATEN GARUT',121,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (60,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',63,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (61,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',71,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (62,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',125,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (63,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',264,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (64,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',119,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (65,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',157,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (66,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',47,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (67,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',79,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (68,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',142,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (69,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',332,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (70,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',393,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (71,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',187,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (72,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',36,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (73,32,'JAWA BARAT',3271,'KOTA BOGOR',370,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (74,32,'JAWA BARAT',3272,'KOTA SUKABUMI',104,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (75,32,'JAWA BARAT',3273,'KOTA BANDUNG',687,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (76,32,'JAWA BARAT',3274,'KOTA CIREBON',242,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (77,32,'JAWA BARAT',3275,'KOTA BEKASI',163,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (78,32,'JAWA BARAT',3276,'KOTA DEPOK',420,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (79,32,'JAWA BARAT',3277,'KOTA CIMAHI',173,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (80,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',67,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (81,32,'JAWA BARAT',3279,'KOTA BANJAR',50,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (82,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',375,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (83,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',93,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (84,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',132,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (85,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',210,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (86,32,'JAWA BARAT',3205,'KABUPATEN GARUT',140,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (87,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',90,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (88,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',90,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (89,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',110,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (90,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',136,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (91,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',99,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (92,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',67,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (93,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',108,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (94,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',108,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (95,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',60,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (96,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',217,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (97,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',157,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (98,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',134,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (99,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',36,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (100,32,'JAWA BARAT',3271,'KOTA BOGOR',219,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (101,32,'JAWA BARAT',3272,'KOTA SUKABUMI',90,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (102,32,'JAWA BARAT',3273,'KOTA BANDUNG',400,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (103,32,'JAWA BARAT',3274,'KOTA CIREBON',134,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (104,32,'JAWA BARAT',3275,'KOTA BEKASI',260,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (105,32,'JAWA BARAT',3276,'KOTA DEPOK',337,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (106,32,'JAWA BARAT',3277,'KOTA CIMAHI',79,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (107,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',53,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (108,32,'JAWA BARAT',3279,'KOTA BANJAR',28,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (109,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',655,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (110,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',269,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (111,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',360,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (112,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',363,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (113,32,'JAWA BARAT',3205,'KABUPATEN GARUT',260,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (114,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',134,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (115,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',150,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (116,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',186,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (117,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',385,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (118,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',114,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (119,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',119,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (120,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',273,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (121,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',158,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (122,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',187,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (123,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',423,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (124,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',1272,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (125,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',174,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (126,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',56,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (127,32,'JAWA BARAT',3271,'KOTA BOGOR',447,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (128,32,'JAWA BARAT',3272,'KOTA SUKABUMI',235,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (129,32,'JAWA BARAT',3273,'KOTA BANDUNG',671,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (130,32,'JAWA BARAT',3274,'KOTA CIREBON',358,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (131,32,'JAWA BARAT',3275,'KOTA BEKASI',1758,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (132,32,'JAWA BARAT',3276,'KOTA DEPOK',519,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (133,32,'JAWA BARAT',3277,'KOTA CIMAHI',241,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (134,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',170,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (135,32,'JAWA BARAT',3279,'KOTA BANJAR',37,'ORANG',2020);
