CREATE TABLE mytable(
   id                  INTEGER  NOT NULL PRIMARY KEY 
  ,kode_provinsi       INTEGER  NOT NULL
  ,nama_provinsi       VARCHAR(10) NOT NULL
  ,kode_kabupaten_kota INTEGER  NOT NULL
  ,nama_kabupaten_kota VARCHAR(23) NOT NULL
  ,jumlah_bidan        INTEGER  NOT NULL
  ,satuan              VARCHAR(5) NOT NULL
  ,tahun               INTEGER  NOT NULL
);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (1,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',938,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (2,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',984,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (3,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',850,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (4,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',581,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (5,32,'JAWA BARAT',3205,'KABUPATEN GARUT',607,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (6,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',623,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (7,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',454,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (8,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',669,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (9,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',915,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (10,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',560,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (11,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',479,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (12,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',1057,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (13,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',922,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (14,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',400,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (15,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',1142,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (16,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',1039,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (17,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',455,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (18,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',91,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (19,32,'JAWA BARAT',3271,'KOTA BOGOR',473,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (20,32,'JAWA BARAT',3272,'KOTA SUKABUMI',318,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (21,32,'JAWA BARAT',3273,'KOTA BANDUNG',877,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (22,32,'JAWA BARAT',3274,'KOTA CIREBON',74,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (23,32,'JAWA BARAT',3275,'KOTA BEKASI',383,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (24,32,'JAWA BARAT',3276,'KOTA DEPOK',629,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (25,32,'JAWA BARAT',3277,'KOTA CIMAHI',218,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (26,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',328,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (27,32,'JAWA BARAT',3279,'KOTA BANJAR',85,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (28,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',1696,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (29,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',1058,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (30,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',843,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (31,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',687,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (32,32,'JAWA BARAT',3205,'KABUPATEN GARUT',1158,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (33,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',516,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (34,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',334,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (35,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',580,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (36,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',1493,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (37,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',586,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (38,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',453,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (39,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',682,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (40,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',596,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (41,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',516,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (42,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',1385,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (43,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',824,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (44,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',471,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (45,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',129,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (46,32,'JAWA BARAT',3271,'KOTA BOGOR',490,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (47,32,'JAWA BARAT',3272,'KOTA SUKABUMI',304,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (48,32,'JAWA BARAT',3273,'KOTA BANDUNG',347,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (49,32,'JAWA BARAT',3274,'KOTA CIREBON',132,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (50,32,'JAWA BARAT',3275,'KOTA BEKASI',499,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (51,32,'JAWA BARAT',3276,'KOTA DEPOK',181,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (52,32,'JAWA BARAT',3277,'KOTA CIMAHI',265,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (53,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',371,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (54,32,'JAWA BARAT',3279,'KOTA BANJAR',150,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (55,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',1698,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (56,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',1312,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (57,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',843,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (58,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',757,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (59,32,'JAWA BARAT',3205,'KABUPATEN GARUT',1264,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (60,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',962,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (61,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',334,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (62,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',588,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (63,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',1578,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (64,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',496,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (65,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',555,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (66,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',552,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (67,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',753,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (68,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',527,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (69,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',1454,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (70,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',1081,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (71,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',489,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (72,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',370,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (73,32,'JAWA BARAT',3271,'KOTA BOGOR',530,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (74,32,'JAWA BARAT',3272,'KOTA SUKABUMI',57,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (75,32,'JAWA BARAT',3273,'KOTA BANDUNG',1204,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (76,32,'JAWA BARAT',3274,'KOTA CIREBON',442,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (77,32,'JAWA BARAT',3275,'KOTA BEKASI',232,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (78,32,'JAWA BARAT',3276,'KOTA DEPOK',769,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (79,32,'JAWA BARAT',3277,'KOTA CIMAHI',264,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (80,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',311,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (81,32,'JAWA BARAT',3279,'KOTA BANJAR',159,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (82,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',1378,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (83,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',1311,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (84,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',1332,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (85,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',811,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (86,32,'JAWA BARAT',3205,'KABUPATEN GARUT',1323,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (87,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',1123,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (88,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',760,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (89,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',906,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (90,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',1423,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (91,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',898,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (92,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',726,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (93,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',792,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (94,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',951,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (95,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',421,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (96,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',1432,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (97,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',904,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (98,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',633,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (99,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',370,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (100,32,'JAWA BARAT',3271,'KOTA BOGOR',593,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (101,32,'JAWA BARAT',3272,'KOTA SUKABUMI',346,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (102,32,'JAWA BARAT',3273,'KOTA BANDUNG',855,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (103,32,'JAWA BARAT',3274,'KOTA CIREBON',443,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (104,32,'JAWA BARAT',3275,'KOTA BEKASI',664,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (105,32,'JAWA BARAT',3276,'KOTA DEPOK',631,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (106,32,'JAWA BARAT',3277,'KOTA CIMAHI',199,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (107,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',409,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (108,32,'JAWA BARAT',3279,'KOTA BANJAR',116,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (109,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',1748,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (110,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',1411,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (111,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',1117,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (112,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',2007,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (113,32,'JAWA BARAT',3205,'KABUPATEN GARUT',1445,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (114,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',1210,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (115,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',725,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (116,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',961,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (117,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',1550,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (118,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',552,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (119,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',728,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (120,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',1011,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (121,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',805,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (122,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',612,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (123,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',1516,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (124,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',1623,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (125,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',638,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (126,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',377,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (127,32,'JAWA BARAT',3271,'KOTA BOGOR',607,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (128,32,'JAWA BARAT',3272,'KOTA SUKABUMI',317,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (129,32,'JAWA BARAT',3273,'KOTA BANDUNG',878,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (130,32,'JAWA BARAT',3274,'KOTA CIREBON',494,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (131,32,'JAWA BARAT',3275,'KOTA BEKASI',997,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (132,32,'JAWA BARAT',3276,'KOTA DEPOK',568,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (133,32,'JAWA BARAT',3277,'KOTA CIMAHI',552,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (134,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',638,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (135,32,'JAWA BARAT',3279,'KOTA BANJAR',176,'ORANG',2020);
