CREATE TABLE mytable(
   id                  INTEGER  NOT NULL PRIMARY KEY 
  ,kode_provinsi       INTEGER  NOT NULL
  ,nama_provinsi       VARCHAR(10) NOT NULL
  ,kode_kabupaten_kota INTEGER  NOT NULL
  ,nama_kabupaten_kota VARCHAR(23) NOT NULL
  ,jumlah_bidan        INTEGER  NOT NULL
  ,satuan              VARCHAR(5) NOT NULL
  ,tahun               INTEGER  NOT NULL
);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (1,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',156,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (2,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',62,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (3,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',19,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (4,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',9,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (5,32,'JAWA BARAT',3205,'KABUPATEN GARUT',53,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (6,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',13,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (7,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',24,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (8,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',25,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (9,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',58,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (10,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',40,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (11,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',41,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (12,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',62,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (13,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',38,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (14,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',15,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (15,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',44,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (16,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',43,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (17,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',23,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (18,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',11,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (19,32,'JAWA BARAT',3271,'KOTA BOGOR',136,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (20,32,'JAWA BARAT',3272,'KOTA SUKABUMI',25,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (21,32,'JAWA BARAT',3273,'KOTA BANDUNG',85,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (22,32,'JAWA BARAT',3274,'KOTA CIREBON',29,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (23,32,'JAWA BARAT',3275,'KOTA BEKASI',42,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (24,32,'JAWA BARAT',3276,'KOTA DEPOK',65,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (25,32,'JAWA BARAT',3277,'KOTA CIMAHI',13,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (26,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',32,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (27,32,'JAWA BARAT',3279,'KOTA BANJAR',37,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (28,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',176,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (29,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',68,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (30,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',10,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (31,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',50,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (32,32,'JAWA BARAT',3205,'KABUPATEN GARUT',68,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (33,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',12,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (34,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',46,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (35,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',50,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (36,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',75,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (37,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',40,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (38,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',29,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (39,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',26,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (40,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',64,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (41,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',15,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (42,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',78,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (43,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',60,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (44,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',28,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (45,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',3,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (46,32,'JAWA BARAT',3271,'KOTA BOGOR',82,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (47,32,'JAWA BARAT',3272,'KOTA SUKABUMI',37,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (48,32,'JAWA BARAT',3273,'KOTA BANDUNG',178,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (49,32,'JAWA BARAT',3274,'KOTA CIREBON',15,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (50,32,'JAWA BARAT',3275,'KOTA BEKASI',11,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (51,32,'JAWA BARAT',3276,'KOTA DEPOK',6,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (52,32,'JAWA BARAT',3277,'KOTA CIMAHI',17,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (53,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',0,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (54,32,'JAWA BARAT',3279,'KOTA BANJAR',52,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (55,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',225,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (56,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',85,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (57,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',8,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (58,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',39,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (59,32,'JAWA BARAT',3205,'KABUPATEN GARUT',67,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (60,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',3,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (61,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',45,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (62,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',44,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (63,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',122,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (64,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',46,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (65,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',64,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (66,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',24,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (67,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',46,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (68,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',35,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (69,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',80,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (70,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',63,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (71,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',86,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (72,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',37,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (73,32,'JAWA BARAT',3271,'KOTA BOGOR',82,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (74,32,'JAWA BARAT',3272,'KOTA SUKABUMI',40,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (75,32,'JAWA BARAT',3273,'KOTA BANDUNG',176,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (76,32,'JAWA BARAT',3274,'KOTA CIREBON',0,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (77,32,'JAWA BARAT',3275,'KOTA BEKASI',7,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (78,32,'JAWA BARAT',3276,'KOTA DEPOK',55,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (79,32,'JAWA BARAT',3277,'KOTA CIMAHI',20,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (80,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',11,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (81,32,'JAWA BARAT',3279,'KOTA BANJAR',32,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (82,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',216,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (83,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',92,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (84,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',94,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (85,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',108,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (86,32,'JAWA BARAT',3205,'KABUPATEN GARUT',95,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (87,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',73,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (88,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',82,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (89,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',62,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (90,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',105,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (91,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',45,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (92,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',65,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (93,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',154,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (94,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',61,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (95,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',16,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (96,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',46,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (97,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',22,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (98,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',90,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (99,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',46,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (100,32,'JAWA BARAT',3271,'KOTA BOGOR',99,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (101,32,'JAWA BARAT',3272,'KOTA SUKABUMI',31,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (102,32,'JAWA BARAT',3273,'KOTA BANDUNG',175,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (103,32,'JAWA BARAT',3274,'KOTA CIREBON',37,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (104,32,'JAWA BARAT',3275,'KOTA BEKASI',105,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (105,32,'JAWA BARAT',3276,'KOTA DEPOK',65,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (106,32,'JAWA BARAT',3277,'KOTA CIMAHI',78,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (107,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',20,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (108,32,'JAWA BARAT',3279,'KOTA BANJAR',17,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (109,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',265,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (110,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',51,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (111,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',66,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (112,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',120,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (113,32,'JAWA BARAT',3205,'KABUPATEN GARUT',78,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (114,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',41,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (115,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',80,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (116,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',86,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (117,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',127,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (118,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',37,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (119,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',76,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (120,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',122,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (121,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',55,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (122,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',14,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (123,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',71,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (124,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',71,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (125,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',84,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (126,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',41,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (127,32,'JAWA BARAT',3271,'KOTA BOGOR',95,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (128,32,'JAWA BARAT',3272,'KOTA SUKABUMI',35,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (129,32,'JAWA BARAT',3273,'KOTA BANDUNG',166,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (130,32,'JAWA BARAT',3274,'KOTA CIREBON',35,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (131,32,'JAWA BARAT',3275,'KOTA BEKASI',100,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (132,32,'JAWA BARAT',3276,'KOTA DEPOK',82,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (133,32,'JAWA BARAT',3277,'KOTA CIMAHI',22,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (134,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',45,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_bidan,satuan,tahun) VALUES (135,32,'JAWA BARAT',3279,'KOTA BANJAR',18,'ORANG',2020);
