CREATE TABLE mytable(
   id                  INTEGER  NOT NULL PRIMARY KEY 
  ,kode_provinsi       INTEGER  NOT NULL
  ,nama_provinsi       VARCHAR(10) NOT NULL
  ,kode_kabupaten_kota INTEGER  NOT NULL
  ,nama_kabupaten_kota VARCHAR(23) NOT NULL
  ,jumlah_dokter_umum  INTEGER  NOT NULL
  ,satuan              VARCHAR(5) NOT NULL
  ,tahun               INTEGER  NOT NULL
);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (1,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',126474,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (2,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',51056,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (3,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',46284,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (4,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',79912,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (5,32,'JAWA BARAT',3205,'KABUPATEN GARUT',62514,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (6,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',33470,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (7,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',20383,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (8,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',20156,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (9,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',53689,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (10,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',21778,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (11,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',20684,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (12,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',43102,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (13,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',35351,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (14,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',19976,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (15,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',46520,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (16,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',73617,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (17,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',32807,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (18,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',6720,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (19,32,'JAWA BARAT',3271,'KOTA BOGOR',21324,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (20,32,'JAWA BARAT',3272,'KOTA SUKABUMI',6535,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (21,32,'JAWA BARAT',3273,'KOTA BANDUNG',46628,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (22,32,'JAWA BARAT',3274,'KOTA CIREBON',5960,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (23,32,'JAWA BARAT',3275,'KOTA BEKASI',55682,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (24,32,'JAWA BARAT',3276,'KOTA DEPOK',46096,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (25,32,'JAWA BARAT',3277,'KOTA CIMAHI',11875,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (26,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',13097,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (27,32,'JAWA BARAT',3279,'KOTA BANJAR',4307,'ORANG',2016);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (28,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',127203,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (29,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',50252,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (30,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',46972,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (31,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',79789,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (32,32,'JAWA BARAT',3205,'KABUPATEN GARUT',57424,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (33,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',32844,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (34,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',19664,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (35,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',19839,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (36,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',40953,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (37,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',21403,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (38,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',20023,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (39,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',30418,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (40,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',27302,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (41,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',19831,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (42,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',46060,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (43,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',80227,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (44,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',34933,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (45,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',6601,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (46,32,'JAWA BARAT',3271,'KOTA BOGOR',21205,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (47,32,'JAWA BARAT',3272,'KOTA SUKABUMI',6461,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (48,32,'JAWA BARAT',3273,'KOTA BANDUNG',45191,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (49,32,'JAWA BARAT',3274,'KOTA CIREBON',5897,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (50,32,'JAWA BARAT',3275,'KOTA BEKASI',56143,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (51,32,'JAWA BARAT',3276,'KOTA DEPOK',46840,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (52,32,'JAWA BARAT',3277,'KOTA CIMAHI',11801,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (53,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',12878,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (54,32,'JAWA BARAT',3279,'KOTA BANJAR',3304,'ORANG',2017);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (55,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',127781,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (56,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',51182,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (57,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',46972,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (58,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',79612,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (59,32,'JAWA BARAT',3205,'KABUPATEN GARUT',61051,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (60,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',32657,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (61,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',23350,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (62,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',19514,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (63,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',50176,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (64,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',21020,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (65,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',19631,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (66,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',29942,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (67,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',35848,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (68,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',19662,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (69,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',45558,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (70,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',81869,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (71,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',34613,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (72,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',6478,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (73,32,'JAWA BARAT',3271,'KOTA BOGOR',21113,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (74,32,'JAWA BARAT',3272,'KOTA SUKABUMI',6381,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (75,32,'JAWA BARAT',3273,'KOTA BANDUNG',44422,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (76,32,'JAWA BARAT',3274,'KOTA CIREBON',5834,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (77,32,'JAWA BARAT',3275,'KOTA BEKASI',56551,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (78,32,'JAWA BARAT',3276,'KOTA DEPOK',47550,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (79,32,'JAWA BARAT',3277,'KOTA CIMAHI',11713,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (80,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',13265,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (81,32,'JAWA BARAT',3279,'KOTA BANJAR',3238,'ORANG',2018);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (82,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',128293,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (83,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',48541,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (84,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',45277,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (85,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',79389,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (86,32,'JAWA BARAT',3205,'KABUPATEN GARUT',55955,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (87,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',31560,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (88,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',18940,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (89,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',19196,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (90,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',39998,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (91,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',20647,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (92,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',19230,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (93,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',29476,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (94,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',26669,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (95,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',19483,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (96,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',45032,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (97,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',83495,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (98,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',34276,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (99,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',6358,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (100,32,'JAWA BARAT',3271,'KOTA BOGOR',21010,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (101,32,'JAWA BARAT',3272,'KOTA SUKABUMI',6301,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (102,32,'JAWA BARAT',3273,'KOTA BANDUNG',43647,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (103,32,'JAWA BARAT',3274,'KOTA CIREBON',5773,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (104,32,'JAWA BARAT',3275,'KOTA BEKASI',56937,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (105,32,'JAWA BARAT',3276,'KOTA DEPOK',48242,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (106,32,'JAWA BARAT',3277,'KOTA CIMAHI',11623,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (107,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',12413,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (108,32,'JAWA BARAT',3279,'KOTA BANJAR',3171,'ORANG',2019);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (109,32,'JAWA BARAT',3201,'KABUPATEN BOGOR',128743,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (110,32,'JAWA BARAT',3202,'KABUPATEN SUKABUMI',47673,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (111,32,'JAWA BARAT',3203,'KABUPATEN CIANJUR',44426,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (112,32,'JAWA BARAT',3204,'KABUPATEN BANDUNG',79131,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (113,32,'JAWA BARAT',3205,'KABUPATEN GARUT',55188,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (114,32,'JAWA BARAT',3206,'KABUPATEN TASIKMALAYA',30912,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (115,32,'JAWA BARAT',3207,'KABUPATEN CIAMIS',18589,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (116,32,'JAWA BARAT',3208,'KABUPATEN KUNINGAN',18884,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (117,32,'JAWA BARAT',3209,'KABUPATEN CIREBON',39534,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (118,32,'JAWA BARAT',3210,'KABUPATEN MAJALENGKA',20284,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (119,32,'JAWA BARAT',3211,'KABUPATEN SUMEDANG',18834,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (120,32,'JAWA BARAT',3212,'KABUPATEN INDRAMAYU',29020,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (121,32,'JAWA BARAT',3213,'KABUPATEN SUBANG',26363,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (122,32,'JAWA BARAT',3214,'KABUPATEN PURWAKARTA',19300,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (123,32,'JAWA BARAT',3215,'KABUPATEN KARAWANG',44495,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (124,32,'JAWA BARAT',3216,'KABUPATEN BEKASI',85125,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (125,32,'JAWA BARAT',3217,'KABUPATEN BANDUNG BARAT',33925,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (126,32,'JAWA BARAT',3218,'KABUPATEN PANGANDARAN',6244,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (127,32,'JAWA BARAT',3271,'KOTA BOGOR',20902,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (128,32,'JAWA BARAT',3272,'KOTA SUKABUMI',6215,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (129,32,'JAWA BARAT',3273,'KOTA BANDUNG',42863,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (130,32,'JAWA BARAT',3274,'KOTA CIREBON',5713,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (131,32,'JAWA BARAT',3275,'KOTA BEKASI',57307,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (132,32,'JAWA BARAT',3276,'KOTA DEPOK',48928,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (133,32,'JAWA BARAT',3277,'KOTA CIMAHI',11528,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (134,32,'JAWA BARAT',3278,'KOTA TASIKMALAYA',12181,'ORANG',2020);
INSERT INTO mytable(id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_dokter_umum,satuan,tahun) VALUES (135,32,'JAWA BARAT',3279,'KOTA BANJAR',3104,'ORANG',2020);
